### ISSUE TITLE
Doublon lors de l'étape 3/8 de la pré-inscription

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#10]
Voici ce qui s'affiche à l'étape 3/8 lorsqu'un nouvel utilisateur s'inscrit sur le site

> Validation du Bulletin d'adhésion
> 
> Merci pour votre adhésion à l'AMAP !
> Un courriel de confirmation vient de vous être envoyé. Pensez à consulter les éléments indésirables.
> Veuillez remettre le chèque à l'ordre de l'AMAP à la prochaine distribution.
> 
> Veuillez remettre le chèque/règlement lors de la première distribution
> 
> Vous pouvez maintenant vous inscrires aux contrats de l'AMAP :

La demande de remise de chèque d'adhésion s'affiche donc 2 fois ...

**Comment by OphyTe** [comment]
Au temps pour moi, je viens de voir qu'on pouvait éditer les messages dans les paramètres. J'ai donc supprimé le doublon dans l'étape `Adhésion AMAP`.

**Comment by sharevb** [comment]
Bonjour, tous les messages sont maintenant personnalisable depuis [hier](https://github.com/comptoirdesappli/amapress/commit/f929b360ee110c2984df7edf31a5841f0e08ccf9)
