### ISSUE TITLE
Message d'erreur persistant sur la page d'édition d'une inscription à un contrat

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#11]
Bonjour,

Je crois que c'est lié à la dernière màj que j'ai faite (de la 87.10 à la 0.90.15).
Depuis, j'ai le message `Notice: Undefined variable: message in /home/amapcoeuln/test/wp-content/plugins/amapress/entities/contrat_adhesion/register.php on line 185` sur la page d'édition d'une inscription d'un amapien à un contrat.
![image](https://user-images.githubusercontent.com/2254975/70382495-64ae0300-195d-11ea-8be2-1aaab6292ff3.png)

**Comment by sharevb** [comment]
Merci pour ce retour. C'est corrigé dans la[ dernière version/commit](https://github.com/comptoirdesappli/amapress/commit/d36a6304f4a1d7c0dfcddb14ed38b98651f193b4)
