### ISSUE TITLE
Mail de confirmation d'inscription à un contrat non envoyé

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#12]
Bonjour,

Je ne sais pas si c'est lié à la dernière màj ou non mais les amapiens se pré-inscrivant à un contrat ne reçoivent plus automatiquement le mail de confirmation. Par contre, si on force l'envoi du mail depuis la page de l'inscription en question (depuis le tableau de bord), ça fonctionne bien.

A noter que je n'ai aucun mail sortant correspondant à cet envoi auto non plus ni aucun mail en erreur ou même en attente.

**Comment by OphyTe** [comment]
Je précise qu'en forçant la notification via le `filter send_contrat_confirm=true` ça ne marche pas mieux ...

**Comment by sharevb** [comment]
Merci pour ce retour. C'est corrigé dans la [dernière version/commit](https://github.com/comptoirdesappli/amapress/commit/30287cbf430cb6742b277b260c12f8b56068efeb)
