### ISSUE TITLE
Choix de la date de 1ère distrib lors de la pre-inscription limité aux dates de distrib de l'année courante

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#13]
Bonjour,

Lors de la pré-inscription, le choix de la date de 1ère distribution se limite aux date de l'année courante (et donc aucune date n'est proposée au delà du 31/12/2019 actuellement).

**Comment by sharevb** [comment]
Merci pour ce retour. La plage de dates proposées comme date de début d'inscription se situe entre la date d'ouverture et la date de clôture. Les dates après la date de clôture ne sont pas proposées.

**Comment by OphyTe** [comment]
Bonjour, en effet, la date de 1ère distribution se situe entre la date d'ouverture et la date de fermeture **des pré-inscriptions en ligne**.

Pourquoi ne pas autoriser les dates sur toute la durée du contrat ?

**Comment by sharevb** [comment]
Bonjour,
Dans les AMAP que nous gérons jusqu'à présent, les référents veulent gérer et autoriser par eux-mêmes les inscriptions qui commence en dehors des périodes d'inscription, par ex, de septembre à avril et si quelqu'un veut commencer plus tard, il doit passer par le référent.
J'ai néanmoins ajouté une option `allow_inscription_all_dates`  dans le commit [Assistant inscription : allow_inscription_all_dates pour autoriser l'inscription à partir de toutes les dates, y compris celles après la date de clôture du contrat](https://github.com/comptoirdesappli/amapress/commit/a33fa02ea3b0099c6f2d663d9aa3101739bc7829)
