### ISSUE TITLE
Lien d'approbation d'un nouvel adhérent inadéquat dans le mail envoyé aux responsables

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#14]
Bonjour,

Sur le mail envoyé aux responsables lors d'une nouvelle pré-adhésion en ligne, le lien vers l'utilisateur à approuver ne redirige pas vers le bon filtre.

En effet, on arrive bien sur la page de gestion des utilisateurs https://monsite/wp-admin/users.php?s&pw-status-query-submit=Filter&new_user_approve_filter=pending&paged=1 mais le filtre "pending" n'est pas activé.

J'ai l'impression que ça devrait plutôt être quelque chose de la forme https://monsite/wp-admin/users.php?s&pw-status-query-submit=Filtrer&new_user_approve_filter-top=pending&paged=1.

**Comment by sharevb** [comment]
Ce mail est géré par le plugin New User Approve. Il semblerait que ce problème lui ait été signalé : https://github.com/picklewagon/new-user-approve/issues/75
