### ISSUE TITLE
Contrat cloturé toujours accessible depuis l'inscription en ligne

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#15]
Bonjour,

Lorsqu'on clôt un contrat, il est toujours disponible sur les écrans d'inscription en ligne à moins de désactiver l'inscription en ligne sur le contrat.

**Comment by sharevb** [comment]
Bonjour,
Ce bug a été corrigé dans le commit [Assistant inscription : ne pas lister les contrats clôturé](https://github.com/comptoirdesappli/amapress/commit/3aee924765d1910689b94d4c6973874feb1468b1)
