### ISSUE TITLE
Annulation en ligne de la pré-inscription à un contrat impossible

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#16]
Bonjour,

L'option "édition de l'inscription jusqu'à sa validation" ne permet pas d'annuler la pré-inscription à un contrat en ligne.

**Comment by OphyTe** [comment]
Bonjour,

ça a l'air de fonctionner sur la 0.90.35 par contre serait-ce possible de mettre le bouton d'annulation directement sur la page listant les contrats ?

En effet, en l'état, ça oblige à modifier le contrat et donc repasser toutes les étapes de l'inscription pour finalement annuler le contrat :-s

**Comment by OphyTe** [comment]
Parfait, merci :-)

**Comment by sharevb** [comment]
Bonjour, désolé je n'ai pas pris le temps de répondre à l'issue avant que vous voyez les changements. C'est en effet implémenté maintenant. Je vais surement aussi ajouter des options pour autoriser/interdire l'annulation séparément de la modification.
