### ISSUE TITLE
Emails groupés envoyés aux "groupes sans modération" (et non aux membres)

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#18]
Bonjour,

Il me semble que les emails envoyés via la fonctionnalité d'emails groupés ne sont pas (ou plus) envoyés qu'aux seuls membres mais bien plus largement (du moins dans ma configuration) à tous les groupes sans modération.

C'est d'ailleurs confirmé par l'affichage du nombre de membres de ce mail groupé (28 dans mon cas) alors qu'un seul groupe (de 13 membres) est coché !

En parcourant les logs des mails sortant, ça confirme bien ce comportement ...

**Comment by sharevb** [comment]
Bonjour,

Merci pour ce retour. 

C'est bien le comportement prévu : les modérateurs et les groupes sans modération faisaient partis des destinataires. Cependant, en effet, ce n'est pas forcement logique. 

J'ai ajouté deux options `Membres ?` pour les inclure ou les exclure (par défaut) des membres/destinataires dans la version [0.94.50](https://github.com/comptoirdesappli/amapress/commit/543d1774efebbd45705e752907f41fd804c7fb80)

**Comment by OphyTe** [comment]
Parfait ! 👍 

Merci beaucoup :-)
