### ISSUE TITLE
Workflow des notifications pour l'inscription en ligne

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#19]
Bonjour,

J'ai refait une passe sur le workflow d'inscription en ligne et j'ai 2-3 remarques sur les notifications envoyées au webmaster :

- est-ce possible de paramétrer l'adresse email des modérateurs pour les demandes d'adhésion ?
- si on passe par l'assistant de pré-inscription AMAPress (inscriptions/?key=xxx), on a les notifications suivantes :
1. notification d'inscription Wordpress par défaut (alors que l'approbation n'est pas encore faite)
2. confirmation d’adhésion AMAPress avec le bulletin attaché (l'approbation n'est toujours pas faite)
3. notification d'inscription New User Approve (une fois l'utilisateur approuvé)
- si on passe par la page d'inscription Wordpress classique (wp-login.php?action=register), on n'a pas la 1ère notif

Peut-on donc calquer le workflow de la pré-inscription en ligne via l'assistant AMAPress sur celui de l'inscription Wordpress classique ?
Dit autrement, peut-on empêcher cette 1ère notification aux utilisateurs dans le process de l'assistant de pré-inscription AMAPress ?

Merci

**Comment by OphyTe** [comment]
Nickel 👍 
Est-ce que de la même manière, si le plugin New User Approve est actif, on pourrait n'envoyer que la demande d'approbation à l'admin (et donc ne pas lui envoyer la notif d'inscription par défaut qui fait doublon) ?

**Comment by sharevb** [comment]
Bonjour, merci pour ces retours, en effet, le message de bienvenue et la notification native Wordpress de nouvelle inscription utilisateur envoyés tous les deux par l'assistant d'inscription en ligne n'étaient pas logiques et le second faisait doublon dans le cas de l'utilisation de New User Approve.
Par ailleurs, les notifications de changement de mot de passe utilisateur (et de nouvelle inscription utilisateur) sont paramétrables dans Tableau de bord>Paramétrage>Paramétrage, onglet Notifications

**Comment by OphyTe** [comment]
Nickel encore une fois 👍 

Merci aussi pour l'info de cette page de paramétrage ... effectivement j'étais passé à côté :-p
