### ISSUE TITLE
Affichage contenu panier

### ISSUE THREAD

**Issue by LoicC04** [comptoirdesappli/amapress#20]
Bonjour,

J'aimerai afficher le contenu de la prochaine distribution sur la page d'accueil (dans un widget, via un shortcode?).
Je pensais que cela fonctionnaire déjà mais il semble que cela fonctionne mais que pour les amapiens connectés.
```
[next-distrib-deliv distrib=2]
```
L'URL suivante est accessible publiquement d'ailleurs : https://les-paniers-de-la-sevre.com/distributions/distribution-du-09-07-2020-a-maison-de-quartier-des-brizeaux/ et donne les infos souhaitées.
Serait-ce possible pour les visiteurs du site ?

**Comment by sharevb** [comment]
Bonjour @LoicC04 ,

Le shortcode `next-distrib-deliv` prend maintenant en charge le mode "non connecté/visiteurs".
Un nouveau shortcode `next-distrib-deliv-paniers` fournit une vue du contenu des paniers pour les prochaines distributions.
