### ISSUE TITLE
Renvoi récurrent d'un email groupé en erreur

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#21]
Bonsoir,

J'ai noté un comportement étonnant sur un email groupé qui était en erreur (à cause d'une adresse mal renseignée comportant un accent).
En effet, l'email à été renvoyé à de multiple reprises (une 15aine de fois en l'espace de quelques heures) aux même destinataires.

Plusieurs questions me viennent alors (désolé :-) ) :
1. Peut-on paramétrer le comportement de ces emails en erreur ? 
2. Est-ce normal qu'Amapress tente désespérément de les renvoyer ? 
3. Ne vaudrait-il mieux pas notifier un webmaster / responsable de ce problème et le laisser traiter ? 
4. Amapress aurait-il la possibilité de savoir à quelles adresses l'email a bien été envoyé et auxquelles ça n'est pas le cas et ainsi ne tenter de le renvoyer qu'à ces dernières ?
5. Je n'ai pas trouvé un endroit listant ces nombreux envois en échec, seul le dernier était mentionné dans l'onglet "Emails sortant en erreur"
6. Après correction de l'adresse mail, le fait de renvoyer le mail (via le bouton "renvoyer") n'a pas eu l'air de prendre en compte la modification
7. J'ai du mal à comprendre la configuration de gestion de la file d'attente d'envoi des mails pour les emails groupés du fait qu'on a la configuration du nombre de mails par lot et l'interval de temps entre chaque envoi de lot (en seconde à priori) et par ailleurs, côté email groupé on peut également définir le nombre de mails envoyé par heure (si on configure le smtp). Est-ce que cette dernière règle s'ajoute au 2 précédentes ?

Merci pour vos réponses

**Comment by sharevb** [comment]
Bonjour,

Nos réponses ci-dessous :
1. _Peut-on paramétrer le comportement de ces emails en erreur ?_ 
=> Il n'existe pas de paramétrage à l'heure actuelle. Il pourrait toutefois être possible de paramétrer un **nombre maximum de tentatives** avant arrêt d'essais de renvoi du mail en erreur
2. _Est-ce normal qu'Amapress tente désespérément de les renvoyer ?_ 
=> La plus part du temps ces erreurs sont transitoires (_erreurs réseau, quota de réception..._) ; aussi un mécanisme de renvoi est en place avec des **intervalles incrémentaux**
3. _Ne vaudrait-il mieux pas notifier un webmaster / responsable de ce problème et le laisser traiter ?_ 
=> Cela pourrait en effet être une alternative après X tentatives. Cependant l'administrateur ne pourra que retenter l'envoi ou supprimer le mail.
4. _Amapress aurait-il la possibilité de savoir à quelles adresses l'email a bien été envoyé et auxquelles ça n'est pas le cas et ainsi ne tenter de le renvoyer qu'à ces dernières ?_
=> Il y a deux cas :
=> **(Configuration recommandée)** Lorsqu'un Email groupé est configuré avec un SMTP (avec les identifiants de l'adresse email de l'Email groupé), il dispose de sa **propre file d'attente** et chaque mail est **distribué individuellement** à chaque destinataire. Dans ce cas, le renvoi en cas d'erreur se fait individuellement.
=> Lorsqu'un Email groupé est configuré sans SMTP, un seul mail est envoyé avec les destinataires en Bcc via la file d'attente globale et donc via l'envoi de mail par l'hébergement. Dans ce cas, le SMTP derrière l'envoi de mail de l'hébergement fera ou non les tentatives nécessaires pour renvoyer le mail et cas d'erreur ou renvoyer un bounce à l'admin.
5. _Je n'ai pas trouvé un endroit listant ces nombreux envois en échec, seul le dernier était mentionné dans l'onglet "Emails sortant en erreur"_
=> Il n'y a pas de log des envois de mails. Les éventuelles erreurs sont logguées dans le fichier de log PHP si celui-ci est configuré, par exemple via le plugin PHP Error Logs (listé dans l'Etat d'Amapress)
6. _Après correction de l'adresse mail, le fait de renvoyer le mail (via le bouton "renvoyer") n'a pas eu l'air de prendre en compte la modification_
=> Le fait de modifier un compte utilisateur ne sera pris en compte que **pour les prochains envois**. De telles modifications ne sont **pas rétroactives sur les mails déjà présents dans les files d'attente ou d'erreur**.
7. _J'ai du mal à comprendre la configuration de gestion de la file d'attente d'envoi des mails pour les emails groupés du fait qu'on a la configuration du nombre de mails par lot et l'interval de temps entre chaque envoi de lot (en seconde à priori) et par ailleurs, côté email groupé on peut également définir le nombre de mails envoyé par heure (si on configure le smtp). Est-ce que cette dernière règle s'ajoute au 2 précédentes ?_
=> Comme évoqué plus haut :
=> **(Confguration recommandée)** Lorsqu'un Email groupé est configuré avec un SMTP (avec les identifiants de l'adresse email de l'Email groupé), il dispose de **sa propre file d'attente** et chaque mail est **distribué individuellement** à chaque destinataire suivant la **cadence indiquée dans la configuration de l'Email groupé**.
=> Lorsqu'un Email groupé est configuré sans SMTP, un seul mail est envoyé avec les destinataires en Bcc via la file d'attente globale et donc via l'envoi de mail **par l'hébergement**. Ce dernière est sujet à la cadence imposée par les **paramètres Interval (d'envoi en secondes) et Emails par interval**.

Il est donc recommandé de **configurer les Emails groupés avec le SMTP** de leur compte mail de l'hébergement afin de disposer d'un quota d'envoi séparé et de ne pas ajouter au quota d'envoi de l'hébergement.

Pour OVH, par exemple :
* **Confguration de la file d'attente globale** (Tableau de bord>Réglages>File d'attente & SMTP, onglet Options de la file des emails sortants) : 
	- pas de SMTP Externe
	- Emails par interval : 6
	- Interval : 180s
* **Confguration des Emails groupés** (Tableau de bord>Emails groupés Comptes) :
	- configuration de l'IMAP et du SMTP pour l'adresse email correspondante (un compte mail de l'hébergement OVH), authentification via les identifiants de ce compte mail
	- Emails par heure : entre 50 et 100

**Comment by fabienel** [comment]
BonjourLe site vient 6 fois la confirmation d'adhésion à un nouvel adhérent.Est ce que c'est les même problème que ci dessous ?
Envoyé depuis Yahoo Mail pour Android 
 
  Le dim., nov. 8, 2020 à 14:09, sharevb<notifications@github.com> a écrit :   


Bonjour,

Nos réponses ci-dessous :
   
   - Peut-on paramétrer le comportement de ces emails en erreur ?   
=> Il n'existe pas de paramétrage à l'heure actuelle. Il pourrait toutefois être possible de paramétrer un nombre maximum de tentatives avant arrêt d'essais de renvoi du mail en erreur
   - Est-ce normal qu'Amapress tente désespérément de les renvoyer ?   
=> La plus part du temps ces erreurs sont transitoires (erreurs réseau, quota de réception...) ; aussi un mécanisme de renvoi est en place avec des intervalles incrémentaux
   - Ne vaudrait-il mieux pas notifier un webmaster / responsable de ce problème et le laisser traiter ?   
=> Cela pourrait en effet être une alternative après X tentatives. Cependant l'administrateur ne pourra que retenter l'envoi ou supprimer le mail.
   - Amapress aurait-il la possibilité de savoir à quelles adresses l'email a bien été envoyé et auxquelles ça n'est pas le cas et ainsi ne tenter de le renvoyer qu'à ces dernières ?   
=> Il y a deux cas :   
=> (Configuration recommandée) Lorsqu'un Email groupé est configuré avec un SMTP (avec les identifiants de l'adresse email de l'Email groupé), il dispose de sa propre file d'attente et chaque mail est distribué individuellement à chaque destinataire. Dans ce cas, le renvoi en cas d'erreur se fait individuellement.   
=> Lorsqu'un Email groupé est configuré sans SMTP, un seul mail est envoyé avec les destinataires en Bcc via la file d'attente globale et donc via l'envoi de mail par l'hébergement. Dans ce cas, le SMTP derrière l'envoi de mail de l'hébergement fera ou non les tentatives nécessaires pour renvoyer le mail et cas d'erreur ou renvoyer un bounce à l'admin.
   - Je n'ai pas trouvé un endroit listant ces nombreux envois en échec, seul le dernier était mentionné dans l'onglet "Emails sortant en erreur"   
=> Il n'y a pas de log des envois de mails. Les éventuelles erreurs sont logguées dans le fichier de log PHP si celui-ci est configuré, par exemple via le plugin PHP Error Logs (listé dans l'Etat d'Amapress)
   - Après correction de l'adresse mail, le fait de renvoyer le mail (via le bouton "renvoyer") n'a pas eu l'air de prendre en compte la modification   
=> Le fait de modifier un compte utilisateur ne sera pris en compte que pour les prochains envois. De telles modifications ne sont pas rétroactives sur les mails déjà présents dans les files d'attente ou d'erreur.
   - J'ai du mal à comprendre la configuration de gestion de la file d'attente d'envoi des mails pour les emails groupés du fait qu'on a la configuration du nombre de mails par lot et l'interval de temps entre chaque envoi de lot (en seconde à priori) et par ailleurs, côté email groupé on peut également définir le nombre de mails envoyé par heure (si on configure le smtp). Est-ce que cette dernière règle s'ajoute au 2 précédentes ?   
=> Comme évoqué plus haut :   
=> (Confguration recommandée) Lorsqu'un Email groupé est configuré avec un SMTP (avec les identifiants de l'adresse email de l'Email groupé), il dispose de sa propre file d'attente et chaque mail est distribué individuellement à chaque destinataire suivant la cadence indiquée dans la configuration de l'Email groupé.   
=> Lorsqu'un Email groupé est configuré sans SMTP, un seul mail est envoyé avec les destinataires en Bcc via la file d'attente globale et donc via l'envoi de mail par l'hébergement. Ce dernière est sujet à la cadence imposée par les paramètres Interval (d'envoi en secondes) et Emails par interval.

Il est donc recommandé de configurer les Emails groupés avec le SMTP de leur compte mail de l'hébergement afin de disposer d'un quota d'envoi séparé et de ne pas ajouter au quota d'envoi de l'hébergement.

Pour OVH, par exemple :
   
   - Confguration de la file d'attente globale (Tableau de bord>Réglages>File d'attente & SMTP, onglet Options de la file des emails sortants) :      
      - pas de SMTP Externe
      - Emails par interval : 6
      - Interval : 180s

   - Confguration des Emails groupés (Tableau de bord>Emails groupés Comptes) :      
      - configuration de l'IMAP et du SMTP pour l'adresse email correspondante (un compte mail de l'hébergement OVH), authentification via les identifiants de ce compte mail
      - Emails par heure : entre 50 et 100

**Comment by sharevb** [comment]
Bonjour @fabienel 

Non, en l'occurrence dans votre cas, adhésion HelloAsso, c'est HelloAsso qui a appelé le callback 6 fois
