### ISSUE TITLE
Calendrier iCal - problème de remontée des évènements d'un contrat

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#22]
Bonjour,

J'ai regardé en détail ce qui remontait dans le calendrier ical généré par Amapress et j'ai quelques remarques :

1. Aucun des évènements d'un de mes contrats ne remonte dans le calendrier (ni encaissements ni distributions) ... Pour les autres c'est ok. Pourtant il est bien visible depuis la page "Mes contrats". 
A noter que les évènements de ce contrat n'apparaissent pas non plus dans le calendrier de mes co-adhérents ...
1. Le lieu des évènements est valorisé avec le nom du lieu de distribution et non son adresse - pas compatible avec les GPS du coup.
1. Quand les numéros de chèques ne sont pas précisés, le descriptif des encaissement ressemble à "Vous allez être encaissé du chèque numéro d'un montant de ...".
1. Ça pourrait être intéressant, dans le descriptif des encaissements, de rappeler le numéro du règlement ainsi que le nombre de règlements restant au contrat. Par exemple "règlement 5 d'un montant de XX€ - il reste 7 règlements à venir à ce contrat".
1. Le terme d'encaissement est plutôt dédié au bénéficiaire du règlement. J'aurais plutôt mis simplement  "paiement" par exemple ...
1. Les encaissements sont fixés à 00h00 et non en journée complète
1. Le rappel de la date dans le descriptif des encaissements n'est pas nécessaire à mon avis
1. Pourquoi ne pas mettre le nom du produit dans le nom des évènements de type encaissement (afin de savoir d'un coup d’œil de quoi il s'agit) ? Par exemple "Paiement du contrat Légumes"

Voilà, je crois que j'ai fait le tour 😄

**Comment by sharevb** [comment]
Bonjour,

Merci pour ces retours et idées d'amélioration 👍 

> 2. Le lieu des évènements est valorisé avec le nom du lieu de distribution et non son adresse - pas compatible avec les GPS du coup.

Les lieux sont maintenant valorisés par leur [nom, leur adresse et leur coordonnées GPS](https://github.com/comptoirdesappli/amapress/commit/f96019bad176a41a040e684b1b2588f2f4a3939e). Quelques corrections structurelles du flux ont également été intégrées

> 3. Quand les numéros de chèques ne sont pas précisés, le descriptif des encaissement ressemble à "Vous allez être encaissé du chèque numéro d'un montant de ...".
> 4. Ça pourrait être intéressant, dans le descriptif des encaissements, de rappeler le numéro du règlement ainsi que le nombre de règlements restant au contrat. Par exemple "règlement 5 d'un montant de XX€ - il reste 7 règlements à venir à ce contrat".
> 5. Le terme d'encaissement est plutôt dédié au bénéficiaire du règlement. J'aurais plutôt mis simplement  "paiement" par exemple ...
> 6. Les encaissements sont fixés à 00h00 et non en journée complète
> 7. Le rappel de la date dans le descriptif des encaissements n'est pas nécessaire à mon avis
> 8. Pourquoi ne pas mettre le nom du produit dans le nom des évènements de type encaissement (afin de savoir d'un coup d’œil de quoi il s'agit) ? Par exemple "Paiement du contrat Légumes"

L'intégration des[ règlements dans le calendrier](https://github.com/comptoirdesappli/amapress/commit/f82c8553b84277b8b3f60b9c4f52669a2a830929) a été amélioré suivant ces différentes suggestions.

**Comment by OphyTe** [comment]
Perfect ! 👍 

Sur Google Agenda, les événements de paiement n'apparaissent toujours pas en journée complète par contre mais comme événements de 00h00 à 23h59.

Rien de bien grave ceci dit, ça me va très bien comme ça.

Merci

**Comment by OphyTe** [comment]
Je viens d'importer le calendrier en question sous Outlook et j'ai l'impression que c'est Google Calendar qui n'interprète pas correctement les données car le contrat qui n'apparaissait pas sous Google Calendar apparaît bien sous Outlook ...

Par contre, il y a un petit soucis sur l'affichage de l'adresse sous Outlook, il concatène le nom du producteur avec l'adresse, sans espace ...

**Comment by sharevb** [comment]
Bonjour,

Ce [commit ](https://github.com/comptoirdesappli/amapress/commit/c8ad81c5481eb2357f5d4c6a76c78f2dec3c60ac) corrige un bug de duplication des UID dans le ICAL qui peut probablement être la cause de l'absence de certains évènements dans le calendrier Google.
