### ISSUE TITLE
Bug sur la répartition des règlements pour un contrat

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#24]
Bonjour,

J'ai l'impression qu'il y a un bug pour l'un de mes contrats (Choix multiple - quantités libres) au niveau de la répartition.

Il y a 10 règlements configurés (pour 10 livraisons) et dans les 3 tableaux récapitulatifs (sommes dues, par date ou par producteur) je vois bien les montants attendus (13€ par livraison) par contre au niveau de la synthèse ou du tableau récap des sommes dues, j'ai 
```
Vous avez choisi le(s) panier(s) "Sac de 4Kg, Jus de pommes" pour 10 distribution(s) pour un montant total de 128,50 € (10 chq. (9 chèque(s) de 0.00 € et 1 12 de 20.50 €))
```

J'ai essayé de jouer sur les différentes options "`Paiement mensuel`", "`Répartition des règlements`" et "`Proposition de répartition`" mais j'ai du mal à les comprendre ...

Au passage, 3 nouvelles petites idées d'amélioration 😉 : 

* pour simplifier l'édition de la répartition des règlements, serait-il possible de rajouter une checkbox "1 règlement par distribution" ? Ca éviterait d'avoir à saisir les date de remise de chèques ET cette répartition ...
* dans les tableaux récapitulatifs par date et par producteur, serait-ce possible de rajouter - quand il y a lieu de le faire - un sous-total par date ou par producteur qui prendrait en compte les différents produits ET les éventuels dons ?
* en terme d'affichage, ça pourrait alléger les tableaux récap par date et producteur de fusionner les cellules des 1ère et 2ième colonnes pour les mêmes dates/producteurs.

Merci

**Comment by OphyTe** [comment]
Je viens de remarquer que le montant total de 128,50€ est correct !
Le prix du panier est bien de 12,50€ par contre l'AMAP a choisi d'arrondir à l'entier supérieur pour faciliter la compta du producteur et j'ai donc 10 chèques de 13€.
C'est peut-être ça qui a causé le problème à la base par contre si je repasse les 10 règlements sur 12,85€, ça ne règle pas le soucis ...

**Comment by sharevb** [comment]
Bonjour,

A priori, tout devrait être réglé
