### ISSUE TITLE
[Nouvelle fonctionnalité] email générique pour les membres du collectif

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#25]
Bonjour,

Une question m'a été posée par un de nos référents : est-ce possible d'utiliser des boîtes génériques partagée par plusieurs référents ?

L'idée est que jusque lors, nous fonctionnions avec des adresses dédiées à chaque type de contrat (une pour les référents du contrat légume, une autre pour les référents du contrat fruits, etc ...).
L'intérêt d'un tel système était que chacun des référents d'un contrat avaient l'intégralité des infos, des échanges qui avaient eu lieu. Ca permettait aussi de suivre les actions à faire / à suivre par un jeu de classement des messages (A faire / A diffuser / En cours de traitement / etc ). Enfin, pour les référents, ça leur évitait de mélanger les messages dédiés à leur rôle de ceux qui leur étaient envoyés en tant qu'amapien lambda.

J'ai bien conscience que le fonctionnement actuel d'Amapress ne permet pas l'utilisation de ces adresses génériques qui ne peuvent apparaître sur plusieurs profils. Le seul palliatif que je vois serait de ne mettre en référents que des users fictif (M. Référents Légumes, M. Référents Fruits, etc ...) à qui seraient associées ces adresses génériques. C'est un peu impersonnel je trouve.

L'idée de cette fonctionnalité serait donc d'ajouter un champ "email générique" à chaque contrat. Toute communication aux référents seraient donc envoyées à cette adresse et non aux référents directement. Libre à eux ensuite de rediriger les messages vers leur boîte perso s'ils le souhaitent.

J'imagine même que la messagerie pourrait du coup permettre l'envoi de message depuis ces adresses (via une configuration du smtp de l'adresse en question) et que ce fonctionnement pourrait s'étendre à tout type de rôle défini sur le site ... 😄

**Comment by sharevb** [comment]
Bonjour,

Après analyse de la faisabilité, il s'avère que ce mécanisme serait trop complexe à implémenter et à maintenir.

Par contre, il est tout à fait possible de faire avec un compte générique autonome :
- Adresse email générique
- Identifiant générique
- Prénom : soit _Référent XXX_, soit un _espace blanc_
- Nom : **liste des noms de référents**
- Rôle : Amap Référent producteur

Cela permet : 
- de ne pas être totalement anonyme, les noms étant affichés
- de mettre plus simplement les membres du collectif à jour
- les référents gardent leur compte amapien séparé
- cela ne perturbe en rien le mécanisme d'envoi de mail actuel

**Comment by OphyTe** [comment]
J'avais pas pensé à l'édition du nom qui porte les noms des référents.
Ça me va, et merci pour l'analyse 😄
