### ISSUE TITLE
Y a-t-il moyen de modifier les référents d'un contrat existant ?

### ISSUE THREAD

**Issue by OphyTe** [comptoirdesappli/amapress#26]
Bonjour,

Tout est dans la question, j'ai oublié des référents sur certains de nos contrats et je ne trouve pas le moyen de modifier ce point en particulier.

J'ai regardé via l'édition avancée des contrats en question ou directement depuis les fiches des référents à ajouter et je n'ai rien trouvé permettant de faire cette action.

Si ça n'est pas possible, quel serait le meilleur moyen de contournement ?
Faut-il dupliquer le contrat et ré-importer toutes les infos liées ?

**Comment by sharevb** [comment]
Bonjour,

Le changement des référents se fait soit au niveau Production (Tableau de bord>Gestion Contrats> Productions) soit au niveau Producteur (Tableau de bord>Gestion Contrats> Productions).

**Comment by OphyTe** [comment]
Nickel, merci 😄
