### ISSUE TITLE
Impossibilité de créer de nouveaux emails groupés

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [comptoirdesappli/amapress#27]
Bonjour,

Je n'arrive plus à créer de nouveaux emails groupés.
J'ai tenté sur 3 instances d'Amapress que j'ai et j'ai le même comportement : lors de la création de l'email groupé, ça mouline jusqu'à ce que ça tombe en timeout et lorsque je reviens à la liste des emails groupés je la vois bien dans la liste. Par contre si je cherche à l'éditer, de la même façon ça mouline jusqu'à tomber en timeout.
Rien dans les logs du serveur.

A noter que 2 de ces instances sont sur une version d'Amapress 0.97.85, la 3ième est en 0.97.0.

**Comment by sharevb** [comment]
Bonjour,

Il semblerait que la configuration SSL/TTS par rapport au port 465 ou 587 soit inversée dans la configuration de ces emails groupés. Apparemment cela cause une attente infinie du côté PHP (voir cette issue sur [PHPMailer](https://github.com/PHPMailer/PHPMailer/issues/638)). C'est corrigé dans la version 0.97.110

**Comment by ThibaultDelaune-pro** [comment]
Bonjour, ça a l'air de marcher merci 👍
