### ISSUE TITLE
GitHub Updater plugin n'a pas un en-tête valide

### ISSUE THREAD

**Issue by JOduMonT** [comptoirdesappli/amapress#28]
bonjour j'ai installé votre plugin amapress via le `Source Code .zip` sur mon wordpress pour une demo et quand je tente d'installer The `GitHub Updater plugin is required. Install Now »` j'ai ce message d'erreur :  `The plugin does not have a valid header.`

si je click sur `Rafraichir le cache Github Updater` j'ai une erreur: Sorry, you are not allowed to access this page.

**Comment by sharevb** [comment]
bonjour, 

GitHub Updater n'existe en effet plus. Il a été renommé en Git Updater par son auteur.
J'ai mergé la branche develop dans la branche master afin de proposer l'installation de Git Updater au lieu de GitHub Updater. Vous pouvez réinstaller Amapress avec cette nouvelle version.
A noter qu'avec Git Updater, Amapress se met à jour sur la branche develop automatiquement (branche plus à jour)
