### ISSUE TITLE
Problème de fin de line/ retour chariot

### ISSUE THREAD

**Issue by mkdgs** [comptoirdesappli/amapress#3]
Salut, 
Il y a un petit soucis avec les fins de ligne sur certains fichier:
https://github.com/comptoirdesappli/amapress/compare/master...mkdgs:patch-2#diff-f5271cc368ab4e85a946293a87e83534

J'ai voulu proposé un PR mais j'ai renoncé, il y a d'autres fichiers concernés.

**Comment by sharevb** [comment]
Bonjour,

J'ai harmonisé les retours à ligne en "\n" sur la branche develop : https://github.com/comptoirdesappli/amapress/tree/develop

**Comment by sharevb** [comment]
Les line endings ont également été harmonisé en \n sur la branche master. Est-ce que cela a résolu votre problème ?
