### ISSUE TITLE
Création d'un second Producteur

### ISSUE THREAD

**Issue by LoicC04** [comptoirdesappli/amapress#4]
Bonjour,

Lorsque j'essaie de créer un autre producteur via le lien suivant : 
monsite.fr/wp-admin/post-new.php?post_type=amps_producteur

J'obtiens le message d'erreur suivant : **Producteur invalide : pas d'utilisateur associé**

J'ai identifié [producteur/register.php](https://github.com/comptoirdesappli/amapress/blob/develop/entities/producteur/register.php#L34) comme émettant le message mais je ne comprends pas pourquoi.
J'ai bien 2 autre utilisateurs déclarés comme Amap Producteur.

Wordpress version : 5.0.3
Amapress : Branch develop Version 0.67.50 (mise à jour en date du 05/02/2019)
PHP : 5.6

**Comment by sharevb** [comment]
Ce message ne devait être affiché qu'en cas d'édition et pas en cas d'ajout. C'est corrigé dans les branches master et develop dans la version [0.68.15](https://github.com/comptoirdesappli/amapress/releases/tag/0.68.15)

**Comment by LoicC04** [comment]
Merci pour la correction ça marche !
