### ISSUE TITLE
Contrat principal obligatoire ?

### ISSUE THREAD

**Issue by LoicC04** [comptoirdesappli/amapress#5]
Dans notre AMAP, nous avons 2 statuts qui permettent l'un de pas s'engager auprès des légumes mais d'accéder aux autres contrats et l'autre de prendre les légumes avant tout. En gros, nous n'avons pas d'obligation de prendre un contrat en particulier.

Est-ce qu'un contrat principale est obligatoire ?
[Contrôle de la présence d'un contrat principale contrat_adhesion/shortcodes.php](https://github.com/comptoirdesappli/amapress/blob/develop/entities/contrat_adhesion/shortcodes.php#L251)

**Comment by sharevb** [comment]
Un contrat principal (Légumes) doit être défini pour le bon fonctionnement d'Amapress. 
Dans la mesure où vous n'avez pas d'obligation de prendre un contrat en particulier dans votre Amap, nous avons ajouté un argument check_principal qui, passé à false, rend possible l'inscription à n'importe quel contrat configuré. Déployé dans la version [0.68.15](https://github.com/comptoirdesappli/amapress/releases/tag/0.68.15).
Vous pouvez configurer deux pages de pré-inscriptions suivant vos deux statuts afin de permettre aux amapiens dûments autorisés à ne pas avoir de contrat Légumes

**Comment by LoicC04** [comment]
J'ai bien vu la correction apportée mais l'affichage est toujours identique. Je pousse une PR pour expliquer.
Deuxièmement, ce paramètre est à changer à la main dans le code ? Si oui, ce serait mieux d'avoir la main dessus dans une interface de paramétrage

**Comment by sharevb** [comment]
Pull request intégré, merci pour vos retours

**Comment by OphyTe** [comment]
Bonjour,
Si le `check_principal` à false est à faire dans le code, quel est le comportement lors de la mise à jour du plugin par GitHub Updater ?

**Comment by sharevb** [comment]
Bonjour,

`check_principal` est un argument du shortcode de l'assistant de pré inscription en ligne, il reste défini entre les mises à jours. S'il est à `false`, il n'est plus nécessaire de définir de _contrat principal_.
J'ai, par ailleurs, ajouté une _option globale_ `AMAP sans contrat obligatoire/principal` (dans `Tableau de bord>Gestion Contrats>Configuration, onglet Contrats`) pour ne pas avoir à ajouter l'argument `check_principal`
